### ISSUE TITLE
Your gmail account was likely hacked

### ISSUE THREAD

**Issue by Valloric** [vheon/home#1]
@vheon

I sent you an email but you might not have gotten it. Creating a github issue is the only other way I know how to reach you. 

Please check your gmail account for a message from me with the subject "Was your gmail account hacked?" **If you can't find it, your gmail account was compromised (and even if you can, it probably still was).** Change your passwords!

I'd rather not go into detail here since it's a public forum.

**Comment by vheon** [comment]
Yeah I know, I already change the password :( I'm really sorry.

**Comment by Valloric** [comment]
Since you have push access to YCM & ycmd repos, please use two-factor auth on your gmail account (I sent you details in the email). :)

You most likely signed up for github with that email account, which means it can be leveraged to gain full privileges to your github account too. Changing your github password would be prudent as well, as would turning on two-factor auth for github.

**Comment by vheon** [comment]
> as would turning on two-factor auth for github

I'm enabling 2FA right now ;)
